{
    "debug.console.fontFamily": "Fira Code",
    "debug.console.fontSize": 15,
    "debug.console.lineHeight": 36,
    "debug.toolBarLocation": "docked",
    "diffEditor.ignoreTrimWhitespace": false,
    "diffEditor.renderSideBySide": false,
    "editor.bracketPairColorization.enabled": false,
    "editor.colorDecorators": false,
    "editor.cursorStyle": "line-thin",
    //"editor.fontFamily": "Geist Mono",
    "editor.fontFamily": "JetBrains Mono",
    "editor.fontWeight": "400",
    "editor.fontLigatures": true,
    "editor.fontSize": 18,
    "editor.letterSpacing": 0.4,
    "editor.formatOnSave": true,
    "editor.glyphMargin": false,
    "editor.gotoLocation.multipleDeclarations": "goto",
    "editor.gotoLocation.multipleDefinitions": "goto",
    "editor.gotoLocation.multipleImplementations": "goto",
    "editor.gotoLocation.multipleReferences": "goto",
    "editor.gotoLocation.multipleTypeDefinitions": "goto",
    "editor.guides.indentation": false,
    "editor.hideCursorInOverviewRuler": true,
    "editor.lineHeight": 48,
    // "editor.lineNumbers": "off",
    "editor.matchBrackets": "near",
    "editor.minimap.enabled": false,
    "editor.occurrencesHighlight": "off",
    "editor.renderLineHighlight": "none",
    "editor.renderWhitespace": "none",
    "editor.scrollbar.horizontalScrollbarSize": 0,
    "editor.scrollbar.verticalScrollbarSize": 0,
    "symbols.hidesExplorerArrows": false,
    "apc.electron": {
        "frame": false,
        "titleBarStyle": "hiddenInset",
    },
    "apc.header": {
        "height": 45,
        "fontSize": 15,
    },
    "apc.listRow": {
        "height": 24,
        "fontSize": 15
    },
    "apc.stylesheet": {
        ".title-label > h2": "display: none",
        ".editor-actions": "display: none",
        ".nosidebar .inline-tabs-placeholder": "width: 75px",
        ".pane-header": "padding: 0 8px",
        ".pane-body": "padding: 8px",
        ".split-view-view:first-child .pane-header": "display: none !important;",
        ".monaco-list-row": "border-radius: 4px;",
        ".monaco-workbench .monaco-list:not(.element-focused):focus:before": "display: none;"
    },
    "workbench.startupEditor": "none",
    "terminal.integrated.cursorStyle": "underline",
    "terminal.integrated.fontSize": 15,
    "terminal.integrated.lineHeight": 1.85,
    "workbench.statusBar.visible": false,
    "workbench.productIconTheme": "fluent-icons",
    "workbench.iconTheme": "symbols",
    "editor.stickyScroll.enabled": false,
    "workbench.colorTheme": "Github Light Theme",
    "workbench.sideBar.location": "right",
    "[blade]": {
        "editor.defaultFormatter": "shufo.vscode-blade-formatter"
    },
    "explorer.confirmDelete": false,
}
